modules/demo/docs/01_SlideTypes.adoc
resources/themes/reveal.css

Adds new roles that can be combined:
- `.has-gold-background`
- `.has-purple-background`
- `.has-green-background`
- `.has-team-background`
- `.has-puzzle-background`
- `.has-node-background`
Here's a few examples:
In other words, you can use a background color with or without a background image on a `section-title` and/or a `title`.
Removes roles:
- `.section-title.gold`
- `.section-title.purple`
- `.section-title.green`
- `.title.gold`
- `.title.purple`
- `.title.green`
Please note that `.gold`, `.purple` and `.green` are still available on "half columns slide":
```
[.half.left.green,transition="fade-in fade-out"]
== !
[.is-half.left.has-dark-background]
--
Some authors
[circle]
- Edgar Allen Poe
- Sheri S. Tepper
- Bill Bryson
--
[.is-half.right]
--
A normal paragraph.
Line breaks are …
```

Combine background color with images

---

build.gradle
resources/themes/reveal.css

As requested by @ElaineRosenberg 
**Before** 
<kbd>
</kbd>
**After**
<kbd>
</kbd>

Reduce margin and top padding on slides

---

build.gradle
modules/demo/docs/01_SlideTypes.adoc

* added slide describing usage
* for better visuals, it needs configuration options:
* openButton: true
* openSlideNumber: false
I could not figure out how to pass them trough the asciidoc plugin

added jevealjs menu plugin

---

build.gradle
resources/extensions/revealjs-extension-config.js

More specifically remove the button of the menu plugin:

Configure the reveal.js plugins

---

modules/4.0-intro-neo4j/docs/03_IntroductionToCypherQueries.adoc
resources/themes/reveal.css

Before | After
------------ | -------------

Update the admonition style on slides

---

modules/4.0-intro-neo4j/docs/00_AboutThisCourse.adoc
resources/themes/reveal.css

List style: increase the left margin and use a small modifier

---

resources/themes/reveal.css

Fix logo positioning when printing PDF

---

build.gradle
modules/4.0-intro-neo4j/docs/01_Neo4jIsAGraphDatabase.adoc
modules/demo/docs/01_SlideTypes.adoc
resources/templates/slide/ulist.html.slim
resources/themes/reveal.css

- enable the timer by setting `revealjs_totaltime`, which sets the total length of your presentation in seconds
- use a dedicated template for answers (used in the "Check your understanding" sections)
- upgrade to reveal.js 3.9.2
- display all the correct answers at once (is that what you want? do you want to make it configurable? either sequential or all at once?)
Also, I think we could remove the above speaker notes as the correct answers can be seen in the "next slide":

Upgrade to Asciidoctor reveal.js 4.0.1

---

build.gradle

@ElaineRosenberg Do you want to use one branch per version? or do you want to put all versions in the master branch?
```
modules/4.0-neo4j-admin
modules/4.1-neo4j-admin
```
If we keep only one version per branch then we should probably drop the "4.0" in the module name. In this case, master branch will be the documentation of the latest or next version and then we can create branch when the version is released or in maintenance:
```
master
4.0
4.1
```

Update the neo4-version default attribute value

---

modules/4.0-intro-neo4j/docs/01_Neo4jIsAGraphDatabase.adoc
modules/4.0-intro-neo4j/docs/02_TheNeo4jGraphPlatform.adoc
modules/4.0-intro-neo4j/docs/03_IntroductionToCypherQueries.adoc
modules/4.0-intro-neo4j/docs/04_UsingWHEREToFilterQueries.adoc
modules/4.0-intro-neo4j/docs/05_WorkingWithPatternsInQueries.adoc
modules/4.0-intro-neo4j/docs/06_WorkingWithCypherData.adoc
modules/4.0-intro-neo4j/docs/07_ControllingTheQueryChain.adoc
modules/4.0-intro-neo4j/docs/08_ControllingResultsReturned.adoc
modules/4.0-intro-neo4j/docs/09_CreatingNodes.adoc
modules/4.0-intro-neo4j/docs/10_CreatingRelationships.adoc
modules/4.0-intro-neo4j/docs/11_DeletingNodesAndRelationships.adoc
modules/4.0-intro-neo4j/docs/12_MergingData.adoc
modules/4.0-intro-neo4j/docs/13_DefiningConstraintsForYourData.adoc
modules/4.0-intro-neo4j/docs/14_UsingIndexes.adoc
modules/4.0-intro-neo4j/docs/15_UsingQueryBestPractices.adoc
modules/4.0-intro-neo4j/docs/16_OverviewOfImportingDataIntoNeo4j.adoc
modules/4.0-intro-neo4j/docs/17_UsingLOADCSVForImport.adoc
modules/4.0-intro-neo4j/docs/18_UsingAPOCForImport.adoc
modules/4.0-intro-neo4j/docs/19_UsingTheNeo4jAdminToolForImport.adoc
modules/4.0-intro-neo4j/docs/20_UsingAnApplicationForImport.adoc
modules/4.0-neo4j-admin/docs/01_IntroToNeo4j.adoc
modules/4.0-neo4j-admin/docs/02_OverviewOfNeo4jAdministration.adoc
modules/4.0-neo4j-admin/docs/12_ImportingData.adoc
resources/themes/reveal.css

And here's how a "summary" slide will look like:

ref #29 use summary section role

---

modules/4.0-intro-neo4j/docs/01_Neo4jIsAGraphDatabase.adoc
modules/4.0-intro-neo4j/docs/02_TheNeo4jGraphPlatform.adoc
modules/4.0-intro-neo4j/docs/03_IntroductionToCypherQueries.adoc
modules/4.0-intro-neo4j/docs/04_UsingWHEREToFilterQueries.adoc
modules/4.0-intro-neo4j/docs/05_WorkingWithPatternsInQueries.adoc
modules/4.0-intro-neo4j/docs/06_WorkingWithCypherData.adoc
modules/4.0-intro-neo4j/docs/07_ControllingTheQueryChain.adoc
modules/4.0-intro-neo4j/docs/08_ControllingResultsReturned.adoc
modules/4.0-intro-neo4j/docs/09_CreatingNodes.adoc
modules/4.0-intro-neo4j/docs/10_CreatingRelationships.adoc
modules/4.0-intro-neo4j/docs/11_DeletingNodesAndRelationships.adoc
modules/4.0-intro-neo4j/docs/12_MergingData.adoc
modules/4.0-intro-neo4j/docs/13_DefiningConstraintsForYourData.adoc
modules/4.0-intro-neo4j/docs/14_UsingIndexes.adoc
modules/4.0-intro-neo4j/docs/15_UsingQueryBestPractices.adoc
modules/4.0-intro-neo4j/docs/16_OverviewOfImportingDataIntoNeo4j.adoc
modules/4.0-intro-neo4j/docs/17_UsingLOADCSVForImport.adoc
modules/4.0-intro-neo4j/docs/18_UsingAPOCForImport.adoc
modules/4.0-intro-neo4j/docs/19_UsingTheNeo4jAdminToolForImport.adoc
modules/4.0-intro-neo4j/docs/20_UsingAnApplicationForImport.adoc
modules/4.0-neo4j-admin/docs/02_OverviewOfNeo4jAdministration.adoc
modules/4.0-neo4j-admin/docs/12_ImportingData.adoc
modules/demo/docs/01_SlideTypes.adoc
resources/themes/reveal.css

ref #29 use quiz section role

---

resources/templates/course/block_admonition.html.erb

**Before** | **After**
------------ | -------------

Fix admonition label

---

resources/extensions/module_info_tree_processor.rb
resources/templates/course/_extra.css
resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

resolves #48
- if the page/module has no quiz, then the "Check Answers" button won't be visible
- if the page/module has already been validated, then the "Check Answers" button won't be visible
- if the page/module has already been validated, then we show the correct answers
State | Image
---- | ----
Page has no quiz |  ![intro-page-no-quiz](https://user-images.githubusercontent.com/333276/76294640-864bbd00-62b3-11ea-9549-dbb28b0b8a6a.png)
Page has already been validated | ![quiz-validated](https://user-images.githubusercontent.com/333276/76294637-851a9000-62b3-11ea-9830-fc625b327b63.png)
Page has not been validated | ![quiz-pristine](https://user-images.githubusercontent.com/333276/76294635-8481f980-62b3-11ea-9c5b-5679c99377d3.png)

resolves #48 hide grade quiz button and show correct answers

---

buildSrc/src/main/kotlin/com/neo4j/gradle/asciidoctor/AsciidoctorModuleDescriptorPlugin.kt
modules/4.0-intro-neo4j/docs/21_Summary.adoc
resources/extensions/module_info_tree_processor.rb
resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

resolves #52 implement the certificate logic

---

build.gradle
resources/templates/course/document.html.erb

resolves #53
Please note that I get 422 from Intercom:
```json
{"type":"error.list","request_id":"0001nvreg6320it1sveg","errors":[{"code":"422","message":"Cannot have more than 120 active event names"}]}
```
Maybe because the event name is unknown? 
```
event_list: {"data":[{"event_name":"course-demo-course-neo4j-16-overview-importing-data"}]}
```

resolves #53 add the Intercom widget

---

resources/templates/course/_quizzes.js

resolves #49 remove 'Click here to continue...'

---

resources/templates/course/_quizzes.js

resolves #54 check if the token has expired (or will soon expire)

---

resources/themes/reveal.css

Add a bottom margin on list

---

resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

 resolves #58 call Intercom with user info

---

resources/templates/course/_quizzes.js

resolves #65 use localStorage instead of cookies to get the token id

---

resources/templates/course/_quizzes.js

resolves #66 
Based on #69 (ie. merge #69 before)

resolves #66 use localStorage to save quizes status

---

README.adoc
build.gradle
resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb
resources/templates/document.html.erb

resolves #72 use the dev backend when the stage is not production

---

build.gradle

Set the `imagesdir` accordingly.
resolves #74

resolves #74 push images to the corresponding S3 bucket (based on the stage property)

---

build.gradle

If we want to test the quiz we can use the "testing" stage.

Always use the project name as the module name

---

.github/workflows/main.yml

Only convert 4.0-intro-neo4j module in the CI

---

build.gradle

If `-Pstage=production` is defined then pages will be published in "public".

Publish pages in public if the stage is production

---

build.gradle

resolves #88 prefix the module name with _testing_ if we are not using stage=production

---

resources/templates/course/_extra.css
resources/templates/course/document.html.erb

**Menu hide/show (large)**
**Menu show (small)**

Retractable left menu

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/neo4j/gradle/asciidoctor/AsciidoctorModuleDescriptorPlugin.kt
buildSrc/src/main/kotlin/com/neo4j/gradle/wordpress/WordPressPlugin.kt

**Plugins have been published :tada: :tada: :tada:**

Publish Gradle plugins to plugins.gradle.org

---

resources/themes/reveal.css

Add a smaller modifier for large content

---

build.gradle
resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

resolves #101
Please note that the page https://neo4j.com/graphacademy/online-training/introduction-to-neo4j-40/ is currently broken:
This URL is wrong `https://neo4j.com/graphacademy/online-training/introduction-to-neo4j-40/neo4jsandbox.com/js/jwt-decode.min.js`
And as a result, I get the following error in the console:
```
Uncaught ReferenceError: jwt_decode is not defined
at HTMLDocument.<anonymous> ((index):629)
at e (jquery-3.4.1.min.js?ver=3.4.1:2)
at t (jquery-3.4.1.min.js?ver=3.4.1:2)
```
And I cannot "Sign in" or "Enroll" for the course.

resolves #101 check that the user is enrolled

---

resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

resolves #100 use the Auth0 authentication

---

resources/templates/course/_quizzes.js
resources/templates/course/document.html.erb

Always use the production instance to get/set quiz status and check the enrollment

---

resources/templates/course/_quizzes.js

resolves #117 generate the certificate on the last page

---

build.gradle

:tada: :tada: :tada: 
//cc @dfgitn4j
resolves #122

resolves #122 add chalkboard plugin

---

modules/graph-data-modeling/docs/00_AboutThisCourse.adoc

change to gdm instructor notes

---

modules/gds-applied-algos/docs/00_AboutThisCourse.adoc
modules/gds-applied-algos/docs/01_Setup.adoc
modules/gds-applied-algos/docs/02_CategoryHierarchy.adoc
modules/gds-applied-algos/docs/03_OrderingSearchResults.adoc
modules/gds-applied-algos/docs/04_MostRelevantReviews.adoc
modules/gds-applied-algos/docs/05_PhotoRecommendations.adoc
modules/gds-applied-algos/docs/06_Summary.adoc

I have followed the new adoc syntax to the best of my knowledge. I updated the two intro videos you sent me, but haven't touched the solutions videos syntax yet.

Update applied algos with GDSL html syntax

---

build.gradle
modules/gds-applied-algos-exercises/docs/01.adoc
modules/gds-applied-algos-exercises/docs/02.adoc
modules/gds-applied-algos-exercises/docs/03.adoc
modules/gds-applied-algos-exercises/docs/04.adoc
modules/gds-applied-algos-exercises/single-pdf/ExercisesGuide.adoc

It can be generated using: 
```
./gradlew gds-applied-algos-exercises:convertSinglePdf
```
I've added the `ifdef::env-guide[]` condition around the `<a play-topic="..."></a>` links and I'm now using the attribute `guides` defined in the `build.gradle` in the links.

Generate a single PDF for gds applied algos exercises

---

build.gradle

And here's the result using ["HowQueriesWorkInNeo4j"](https://github.com/neo4j-contrib/training-v3/blob/master/modules/4.0-cypher-query-tuning/docs/01_HowQueriesWorkInNeo4j.adoc)
//cc @ElaineRosenberg

Add support for nested lists in the Google Slides converter

---

modules/4.0-intro-graph-algos-exercises/docs/LoadData.adoc
modules/4.0-intro-graph-algos/docs/06_GraphCatalog.adoc
modules/4.0-intro-graph-algos/docs/07_CommunityDetection.adoc

Community detection guided exercises

Community detection guided exercises

---

build.gradle

Here's the command to publish to S3:
```
./gradlew 4.0-cypher-query-tuning:s3UploadSetup -Pstage=production -Ps3-region=us-east-2
```

Publish setup pages to S3

---

modules/4.0-cypher-query-tuning/modules/ROOT/pages/06-cqt-40-summary.adoc
modules/4.0-implementing-graph-data-models/modules/ROOT/pages/05-igdm-40-implementing-graph-data-models-summary.adoc
modules/4.0-intro-graph-algos/modules/ROOT/pages/12-iga-40-summary.adoc
modules/4.0-intro-neo4j/modules/ROOT/pages/22-intro-neo4j-summary.adoc
modules/4.0-neo4j-admin/modules/ROOT/pages/13-basic-neo4j-admin-summary.adoc
modules/gds-applied-algos/modules/ROOT/pages/06-gdsaa-summary.adoc
modules/graph-data-modeling/modules/ROOT/pages/06-graph-data-modeling-summary.adoc
modules/neo4j-administration/modules/ROOT/pages/07-neo4jadmin-3-5-summary.adoc
modules/online-training-v2/modules/ROOT/pages/08-introneo-3-5-summary.adoc
resources/templates/course/document.html.erb

Instead use the `page-certificate` attribute to enable the section.

Remove the explicit Certificate section title

---

modules/4.0-intro-graph-algos/modules/ROOT/pages/enrollment.adoc
modules/4.0-intro-neo4j/modules/ROOT/pages/enrollment.adoc
modules/4.0-neo4j-admin/modules/ROOT/pages/enrollment.adoc
modules/gds-applied-algos/modules/ROOT/pages/enrollment.adoc
modules/graph-data-modeling/modules/ROOT/pages/enrollment.adoc
modules/neo4j-administration/modules/ROOT/pages/enrollment.adoc
modules/online-training-v2/modules/ROOT/pages/enrollment.adoc

Otherwise, the breadcrumbs on Antora will contains two entries.

Use the module's title on the enrollment page

---

.github/workflows/notify.yml

Not sure if `secrets.BUILD_ACCESS_TOKEN` is defined, could you please check @ElaineRosenberg @adam-cowley ?

Notify docs-refresh when something is pushed on master

---

local-antora-playbook.yml
modules/gds-applied-algos/modules/ROOT/pages/01-gdsaa-setup-and-cypher-refresher.adoc

Integrate Yelp dataset agreement block

---

modules/graph-data-modeling/modules/ROOT/pages/01-introduction-graph-data-modeling.adoc

Grammar mistake

---

modules/4.0-intro-neo4j/modules/ROOT/pages/15-using-query-best-practices.adoc

Corrected a typo in the first bullet point of the summary of the best practices

Corrected a Typo

---

modules/4.0-querying/modules/ROOT/pages/03-querying40-working-with-patterns-in-queries.adoc

Added blank space to 03-querying40-working-with-patterns-in-queries.adoc

---

modules/4.0-querying/modules/ROOT/pages/04-querying40-working-with-cypher-data.adoc

Restructured the sentence to make it easier to understand.
It now also better linked with the sentence which precedes it.

Improved readability of 04-querying40-working-with-cypher-data.adoc

---

modules/4.0-updating/modules/ROOT/pages/01-updating40-creating-nodes.adoc

Corrected grammar

---

modules/graph-data-modeling/modules/ROOT/pages/05-refactoring-model.adoc

After spending time on the Neo4J community boards, I've noticed that a lot of newbies don't realize you can have multiple Labels on a node.
In addition, newbies don't seem to realize that Labels are implement as a set of nodes with the same Label, speeding up access, which is why labels are so important.
My proposed rewording is an attempt to emphasize this.  The proposed text might be repeating itself too much.  On the other hand, I think it's worth re-emphasizing.

Minor rewording

---

modules/4.0-best-practices/modules/ROOT/pages/02-best-practices40-using-indexes.adoc

I added a link to Lucene in case a newbie has never heard of Lucene.
Initially, I was confused by how YIELD worked.  I've added some text to clarify how YIELD works.

Add link to Lucene; clarify YIELD node

---

modules/4.0-overview/modules/ROOT/pages/03-overview40-summary.adoc

1.  **Overview**
- Reformatted resources list on summary page for intro into a list
- removed line break in sandbox link
- copy & call to action for the next course in series

Provide clear next steps for a learner at the end of each course

---

modules/4.0-intro-neo4j/modules/ROOT/pages/enrollment.adoc

This course is now chunked into smaller courses.
//cc @ElaineRosenberg @adam-cowley

Hide the Neo4j 4.x introduction course from the listing

---

modules/4.0-intro-neo4j/modules/ROOT/pages/01-neo4j-graph-database.adoc

Better version of the 'what is neo4j video' which also has the new logo and branding.

New 'What is Neo4j' video, updated and new logo

---

browser-guides/4.0-intro-graph-algos-exercises/docs/LouvainModularity.adoc
browser-guides/4.0-intro-graph-algos-exercises/docs/NodeSimilarity.adoc
browser-guides/4.0-intro-graph-algos-exercises/docs/PracticalApplication.adoc
browser-guides/4.0-intro-graph-algos-exercises/docs/TriangleCount.adoc
browser-guides/intro-graph-algos-exercises/docs/04.adoc
modules/4.0-intro-graph-algos/modules/ROOT/pages/07-iga-40-graph-algorithms-workflow.adoc
modules/4.0-intro-graph-algos/modules/ROOT/pages/09-iga-40-community-detection.adoc
modules/4.0-intro-graph-algos/modules/ROOT/pages/10-iga-40-centrality-algorithms.adoc
modules/4.0-intro-graph-algos/modules/ROOT/pages/11-iga-40-similarity-algorithms.adoc
modules/gds-data-science/supplemental/notebooks/02_EDA.ipynb

Minor fixes

---

modules/4.0-querying/modules/ROOT/pages/01-querying40-introduction-to-cypher.adoc

Replace 'of of' with just 'of'.

Fix: replace 'of of' with just 'of'

---

modules/4.0-updating/modules/ROOT/pages/01-updating40-creating-nodes.adoc

Fix: vice versa misspelling

---

modules/4.0-cypher-query-tuning/modules/ROOT/pages/01-cqt-40-how-queries-work-in-neo4j.adoc

correct typos

---

modules/graph-data-modeling/modules/ROOT/pages/04-common-graph-structures.adoc

Found something while reading. Fixed the errors.

Spelling error

---

modules/graph-data-modeling/modules/ROOT/pages/05-refactoring-model.adoc

Typo identified and fixed while reading.

Typo identified and fixed

---

build.gradle

Bintray has now been sunset, the library io.github.mogztter:asciidoctor-googleslides is now longer available.
Since this task is now longer used, I decided to remove the task and the dependency all together.
This pull request should fix the build!

Remove the Google Slides task

---

modules/4.0-overview/modules/ROOT/pages/00-overview40-about.adoc
modules/4.0-overview/modules/ROOT/pages/01-overview40-neo4j-graph-database.adoc
modules/4.0-overview/modules/ROOT/pages/02-overview40-neo4j-graph-platform.adoc
modules/4.0-overview/modules/ROOT/pages/03-overview40-summary.adoc

Thanks for putting together all this great training material.  I figured I could submit some fixes to typos as I go through the training, as a thank you.  This PR is mainly straightforward typo fixes, but it also has a few other minor changes for better clarity or to be consistent with the rest of the docs.  You can just cherry pick whichever changes you agree with.  And let me know if you prefer I submit each change individually using the "Edit this Page" link.  I started with that, but figured it would be quicker/easier to do one PR instead of many for this one training module.

Overview of Neo4j module: Typo fixes and minor changes for clarity and consistency.

---

.github/workflows/notify.yml

master has been renamed main but it's better to use a tag anyway!

Use a tag rather than a branch name
